#!/usr/bin/env python
# coding: utf-8

""" Compare summaries generated by n workers"""

def get_similarity(summary1, summary2): 
    words1 = set(summary1.split()) 
    words2 = set(summary2.split())
    common_words = words1.intersection(words2)
    return float(len(common_words)) / (len(words1) + len(words2) - len(common_words))


with open('C:/Users/LTS WinPro/Desktop/shufflesequences/mythshuff5.txt','r') as summaries:
    lines = summaries.readlines()
    
for x in range(0,len(lines)-1):
    print(get_similarity(lines[x],lines[x+1]))
        
