#!/usr/bin/env python
# coding: utf-8

""" Compare summaries generated by n workers"""

def get_similarity(summary1, summary2): 
    a = set(summary1.split()) 
    b = set(summary2.split())
    c = a.intersection(b)
    return float(len(c)) / (len(a) + len(b) - len(c))


with open('summaries.txt','r') as summaries:
    lines = summaries.readlines()
    
    for x in range(0,len(lines)-1):
        print(get_similarity(lines[x],lines[x+1]))
        
